version: '3'
services:
  ds:
    image: "thegreatvbnz/data-science:latest"
    volumes: 
      - "/home/dmitrymikhailovich_/:/cnt:rw"
    ports:
     - "5100:8888"
    command: jupyter lab --ip 0.0.0.0 --no-browser --allow-root
